export const metadata = {
  title: "Admin | Furnito - A Modern Furniture Store",
  description: "Generated by Next.js",
};

import "../globals.css";

export default function AdminLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
